language: node_js
node_js: node

services:
  - redis

cache:
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
